version: '2'
services:
  book-shop-db:
    image: "postgres:9.6.3"
    ports:
      - "6550:5432"
    network_mode: "book-shop"
    container_name: "book-shop-db"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "book_shop"
    volumes:
      - "book-shop-postgresql:/var/lib/postgresql/data"
volumes:
  book-shop-postgresql:
  
