version: '2'
services:
  book-shop-db:
    image: "postgres:9.6.3"
    ports:
      - "6550:5432"
    network_mode: "book-shop"
    container_name: "book-shop-db"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "book_shop"
    volumes:
      - "book-shop-postgresql:/var/lib/postgresql/data"
  s3-cloudserver:
    image: "scality/s3server"
    ports:
      - "6552:8000"
    network_mode: "book-shop"
    container_name: "s3.docker.test"
    environment:
      SCALITY_ACCESS_KEY_ID: "admin"
      SCALITY_SECRET_ACCESS_KEY: "password"
    volumes:
      - "s3-localData:/usr/src/app/localData"
      - "s3-localMetadata:/usr/src/app/localMetadata"
volumes:
  book-shop-postgresql:
  s3-localData:
  s3-localMetadata:
