version: '2'
services:
  book-shop-db:
    image: "postgres:9.6.3"
    ports:
      - "6550:5432"
    network_mode: "book-shop"
    container_name: "book-shop-db"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "book_shop"
    volumes:
      - "book-shop-postgresql:/var/lib/postgresql/data"
  s3-cloudserver:
    image: "scality/s3server"
    ports:
      - "6552:8000"
    network_mode: "book-shop"
    container_name: "s3.docker.test"
    environment:
      SCALITY_ACCESS_KEY_ID: "admin"
      SCALITY_SECRET_ACCESS_KEY: "password"
    volumes:
      - "s3-localData:/usr/src/app/localData"
      - "s3-localMetadata:/usr/src/app/localMetadata"
  sso-db:
      image: "postgres:9.6.3"
      ports:
        - "5433:5432"
      network_mode: "book-shop"
      container_name: "sso-db"
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "secret"
        POSTGRES_DB: "ssoDB"
      volumes:
        - "sso-postgresql:/var/lib/postgresql/data"
  keycloak:
      image: "jboss/keycloak-postgres:3.2.1.Final"
      ports:
        - "8080:8080"
      network_mode: "book-shop"
      container_name: "keycloak"
      environment:
        KEYCLOAK_USER: "admin"
        KEYCLOAK_PASSWORD: "admin"
        PROXY_ADDRESS_FORWARDING: "true"
        POSTGRES_DATABASE: "ssoDB"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "secret"
        POSTGRES_PORT_5432_TCP_ADDR: "sso-db"
        POSTGRES_PORT_5432_TCP_PORT: 5432
volumes:
  sso-postgresql:
  book-shop-postgresql:
  s3-localData:
  s3-localMetadata:
